<a href="<?= $this->url('animal/add') ?>">Tier hinzufügen</a>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Erstellt am</th>
            <th>Aktionen</th>
        </tr>
    </thead>
<?php foreach($animals as $animal) : ?>
    <tr>
        <td><?= $this->escapeHtml($animal->id) ?></td>
        <td><?= $this->escapeHtml($animal->name) ?></td>
        <td><?= $this->escapeHtml($animal->createdAt) ?></td>
        <td>
            <a href="<?= $this->url('animal/edit', ['id' => $animal->id]) ?>">bearbeiten</a>
            <a href="<?= $this->url('animal/delete', ['id' => $animal->id]) ?>">löschen</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>