<a href="<?= $this->url('animal') ?>">zurück zur Tierübersicht</a>
<div class="container-fluid">
    <?php if ($animal->imagePath !== null): ?>
    <div class="row">
        <div class="col-md-12"><img src="<?= $animal->imagePath ?>" alt="Foto der Katze"></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->breed !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Rasse:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->breed ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->name !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Name:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->name ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->color !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Farbe:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->color ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->dateOfBirth !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Geburtsdatum:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->dateOfBirth ?></div>
    </div>
    <?php endif; ?>
    
    <div class="row">
        <div class="col-xs-6 col-md-4">Geschlecht:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->isMale ? 'männlich' : 'weiblich' ?></div>
    </div>
    
    <?php if ($animal->location !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Aufenthaltsort:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->location->name ?></div>
    </div>
    <?php endif; ?>
    
    <div class="row">
        <div class="col-xs-6 col-md-4">Kastriert:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->isCastrated ? 'ja' : 'nein' ?></div>
    </div>
    
    <?php if ($animal->isCastrated && $animal->castrationDate !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Kastrationsdatum:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->castrationDate ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->firstVaccination !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Erste Impfung:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->fistVaccination ?></div>
    </div>
    
        <?php if ($animal->secondVaccination !== null): ?>
        <div class="row">
            <div class="col-xs-6 col-md-4">Zweite Impfung:</div>
            <div class="col-xs-12 col-md-8"><?= $animal->secondVaccination ?></div>
        </div>
        <?php endif; ?>
    <?php endif; ?>
    
    <?php if ($animal->nextVaccination !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Nächste Impfung:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->nextVaccination ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->leftTattoo !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Nächste Impfung:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->nextVaccination ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->rightTattoo !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Nächste Impfung:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->nextVaccination ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->chip !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Chip:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->chip ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->distinguishingMarks !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Besondere Kennzeichen:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->distinguishingMarks ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->comments !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Bemerkungen:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->comments ?></div>
    </div>
    <?php endif; ?>
    
    <?php if ($animal->deceased !== null): ?>
    <div class="row">
        <div class="col-xs-6 col-md-4">Verstorben:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->deceased ? 'ja' : 'nein' ?></div>
    </div>
    
        <?php if ($animal->causeOfDeath !== null): ?>
        <div class="row">
            <div class="col-xs-6 col-md-4">Todesursache:</div>
            <div class="col-xs-12 col-md-8"><?= $animal->causeOfDeath ?></div>
        </div>
        <?php endif; ?>
    <?php endif; ?>
    
    <div class="row">
        <div class="col-xs-6 col-md-4">Wohnungskatze:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->isIndoorCat ? 'ja' : 'nein' ?></div>
    </div>
    
    <div class="row">
        <div class="col-xs-6 col-md-4">Freigänger:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->isOutdoorCat ? 'ja' : 'nein' ?></div>
    </div>
    
    <div class="row">
        <div class="col-xs-6 col-md-4">Katzenverträglich:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->isCatFriendly ? 'ja' : 'nein' ?></div>
    </div>
    
    <div class="row">
        <div class="col-xs-6 col-md-4">Hundeverträglich:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->isDogFriendly ? 'ja' : 'nein' ?></div>
    </div>
    
    <div class="row">
        <div class="col-xs-6 col-md-4">Kinderverträglich:</div>
        <div class="col-xs-12 col-md-8"><?= $animal->isDogFriendly ? 'ja' : 'nein' ?></div>
    </div>
</div>

